### ISSUE TITLE
deviceuuid KeyError with Samsung Health export data

### ISSUE THREAD

**Issue by kilbyjmichael** [timpyrkov/mhealthdata#1]
I was trying to load Samsung Health data export with this package and am running into this KeyError when calling mhealthdata.ShealthLoader(). I have a samsung phone and watch and only started using it about 2 days ago. I think I can get access to other data to test with to prove whether or not its my data causing the issue and will update here if I do that.

I have tried using the full path, removing the files causing the error and editing the data files to no effect.

**My code:**
```
import mhealthdata

path = 'data'
wdata = mhealthdata.ShealthLoader(path)
```

**Error:**
```
============= RESTART: C:\Users\PVE VM\Documents\samsung_health\mhealth_test.py =============

  0%|          | 0/7 [00:00<?, ?it/s]
  0%|          | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\PVE VM\Documents\samsung_health\mhealth_test.py", line 4, in <module>
    wdata = mhealthdata.ShealthLoader(path)
  File "C:\Users\PVE VM\AppData\Roaming\Python\Python311\site-packages\mhealthdata\dataloader.py", line 575, in __init__
    self.load_data()
  File "C:\Users\PVE VM\AppData\Roaming\Python\Python311\site-packages\mhealthdata\dataloader.py", line 742, in load_data
    df = self.load_jsons(category)
  File "C:\Users\PVE VM\AppData\Roaming\Python\Python311\site-packages\mhealthdata\dataloader.py", line 718, in load_jsons
    df_["deviceuuid"] = np.array([dev[f]] * nrec)
KeyError: 'data\\samsunghealth_xxxxxxxxxxxx_20240130163418\\jsons\\com.samsung.shealth.tracker.pedometer_day_summary\\0\\0fcb0185-cd8c-4157-953f-3026c8807686.binning_data.json'
```

**Comment by kotai2003** [comment]
I have same error with samsung health data.
